version: "0.5"
is_strict: true
processes:
  init_db:
    namespace: init
    command: |
      sh config/devbox/init-db.sh
    depends_on:
      postgresql:
        condition: process_healthy
  # TODO: Configure additional processes, e.g. building packages, starting dev servers, etc.
  # 
  # dev_website:
  #   command: |
  #     pnpm --filter ./packages/website dev
  #   readiness_probe:
  #     http_get:
  #       host: localhost
  #       scheme: http
  #       path: "/"
  #       port: 5173
  #   depends_on:
  #     init_db:
  #       condition: process_completed_successfully
